### ISSUE TITLE
Bugs on the week page

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#102]
- [ ] **Description**
На странице со всем днями. Нет времени, и подпись под картинкой не соответствует Figma . 

**Actual result**
![2022-07-27_15-20-28](https://user-images.githubusercontent.com/85569627/181246232-7a6b8018-0617-412a-a630-61f242a43f66.png)

**Expected result**
 ![2022-07-27_15-27-31](https://user-images.githubusercontent.com/85569627/181246794-61321d89-09ba-40e4-9b2c-a6eeb2b14b4c.png)

**Attachments**
https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=823%3A2757

**Comment by ZelGaDisA** [comment]
мы потом по дизайну удирали, эти строки у нас в другом окне
