### ISSUE TITLE
Bugs on the page of day 

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#103]
- [x] **Description**
Неверные подписи на странице  выбранным днем

**Actual result**
![2022-07-27_16-00-59](https://user-images.githubusercontent.com/85569627/181253305-3b373595-0c69-4774-8a48-138b27106ee1.png)

**Expected result**
![2022-07-27_15-30-27](https://user-images.githubusercontent.com/85569627/181247183-35356852-27e1-4509-8c42-0f1debb39748.png)

**Attachments**
https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=633%3A1363

**Comment by ZelGaDisA** [comment]
close ready(когда определимся что как сделаем нормально)
