### ISSUE TITLE
Wrong number of done sets

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#104]
- [x]  **Description**
 Неверно указано сколько сетов сделано  

**Preconditions**
Ни один сет не выполнен

**Actual result**
Ошибочно показывает, что выполнено три сета 
![2022-07-27_15-22-48](https://user-images.githubusercontent.com/85569627/181247435-50c057cc-dc35-4172-83e0-4f99afc11c28.png)

**Comment by ZelGaDisA** [comment]
ready
