### ISSUE TITLE
The size of text and missed letter

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#107]
- [ ] **Description**
пропущена буква,  размер цифры и ее расположение не соответствует Figma

**Actual result**
![2022-07-27_15-46-04](https://user-images.githubusercontent.com/85569627/181250569-8875938a-0b74-4204-8a95-20d5e96b049d.png)

**Expected result**
![2022-07-27_15-49-20](https://user-images.githubusercontent.com/85569627/181250848-5a6c9907-c80b-4c18-8b76-e52968721798.png)

**Attachments**
https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=633%3A1363

**Comment by ZelGaDisA** [comment]
ready

**Comment by SlavaHeorh** [comment]
Done
