### ISSUE TITLE
Different colour

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#108]
- [x]  **Description**
Цвет галочек и цвет рамки не соответствует Figma

**Actual result**
![2022-07-27_15-55-03](https://user-images.githubusercontent.com/85569627/181252063-7a73d47a-e168-4d02-b285-6401ad496493.png)

**Expected result**
![2022-07-27_15-56-17](https://user-images.githubusercontent.com/85569627/181252222-18e62467-746d-4b81-800e-e9b10e8bd9f3.png)

**Attachments**
https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=633%3A1363

**Comment by ZelGaDisA** [comment]
исправлено
