### ISSUE TITLE
Label demo

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#120]
- [ ] **Description**
Нет надписи DEMO

**Actual result**
![2022-08-01_10-09-59](https://user-images.githubusercontent.com/85569627/182093242-9370a168-377e-44d7-9a39-1c68a0847a14.png)

**Expected result**
![2022-08-01_10-11-51](https://user-images.githubusercontent.com/85569627/182093257-e2e1c0e6-b0b3-4f67-8336-24a3327a1864.png)

**Comment by ZelGaDisA** [comment]
ready issue

**Comment by dmitrivanich** [comment]
Нет ссылки healthuapp.com
