### ISSUE TITLE
[4h] Find and Think over new sitting exercises

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#122]

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=xRI9obPG_aE&ab_channel=HennepinHealthcare (2:21) рука к колену

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=xRI9obPG_aE&ab_channel=HennepinHealthcare (5:33) бицепс сбоку и затем опускание вниз

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=xRI9obPG_aE&ab_channel=HennepinHealthcare (6:38) наклоны всторону с поднятой рукой

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=HfrkguDu1c8&ab_channel=HennepinHealthcare (6:11) наклоны в стороны,руки за головой

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=azv8eJgoGLk&ab_channel=HASfit (1:53) плечи вверх-вниз руки в локте 90 градусов

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=ASXGYu7IFxE&ab_channel=HASfit (27:00) растяжка рук
