### ISSUE TITLE
[8h] Create exersice Biceps Sideways and then Lowering down seated #43

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#131]
https://www.youtube.com/watch?v=xRI9obPG_aE&ab_channel=HennepinHealthcare (5:33) бицепс сбоку и затем опускание вниз

**Comment by tanyashagova** [comment]
Create exercise

**Comment by vladimirlabynko** [comment]
https://github.com/healthUapp/trainer-js/issues/132
