### ISSUE TITLE
Add picture on statistic page

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#139]
- [ ] **Description**
Нет картинки на странице статистики за день, если пользователь еще не выполнил упражнение
Надпись DEMO не посередине страницы 

**Actual result**
![2022-08-04_11-09-53](https://user-images.githubusercontent.com/85569627/182798000-59d4f966-3d0a-4017-b0ea-c7d43f162c31.png)

**Expected result**
https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=1617%3A18644

**Comment by ZelGaDisA** [comment]
ready
