### ISSUE TITLE
Add button back to activities  

### ISSUE THREAD

**Issue by chaychits** [healthUapp/trainer-js#142]
- [ ] No button back to activities on statistic page  

**Actual result**
![2022-08-04_11-31-10](https://user-images.githubusercontent.com/85569627/182802218-5a34e183-25d1-4cd6-b0ae-f28929b4f631.png)

**Expected result**
![2022-08-04_11-38-35](https://user-images.githubusercontent.com/85569627/182803277-61adea25-0d32-4689-8395-65daa82a791d.png)

**Comment by ZelGaDisA** [comment]
done
