### ISSUE TITLE
[6h] Create layout and logic The Main screen according to Figma mokup

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#147]
[Link to Figma ](https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=160%3A151)

**Comment by buyalskaya** [comment]
![Image](https://user-images.githubusercontent.com/97980474/183076486-685cc6ec-3a1e-4b3f-959a-d1c5b90c4abd.PNG)

**Comment by ZelGaDisA** [comment]
ready
