### ISSUE TITLE
[3h] Create layout and logic the Weekly plan screen

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#148]
[Link to Figma](https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=160%3A151)

**Comment by buyalskaya** [comment]
![Image](https://user-images.githubusercontent.com/97980474/183076196-2bc43c2c-a673-4566-a2f8-2b5f9af4f40f.PNG)

**Comment by ZelGaDisA** [comment]
ready
