### ISSUE TITLE
[16h] Add arrows to 5 exercises (on the plugin)

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#166]
[Референс](https://github.com/healthUapp/trainer-js/issues/152)

**Comment by tanyashagova** [comment]
Have added visualization with arrows to the squats and side leg raises exercises

**Comment by tanyashagova** [comment]
Have added visualization with arrows to the leaning tree exercise

**Comment by tanyashagova** [comment]
Added visualization with arrows for the side arms raises exercise

**Comment by tanyashagova** [comment]
Added visualization with arrows for the w-extension-seated exercise
