### ISSUE TITLE
[24] Research hand gesture

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#174]

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=a99p_fAr6e4&ab_channel=IvanGoncharov

**Comment by vladimirlabynko** [comment]
have a problems with tensorflow installation on MAC m1

**Comment by vladimirlabynko** [comment]
https://developer.apple.com/metal/tensorflow-plugin/
HELP solve problem

**Comment by vladimirlabynko** [comment]
hand gesture recognizer complited

**Comment by vladimirlabynko** [comment]
https://github.com/healthUapp/trainer/commit/b15f3debcd33aac2bc2eed480ef28744db64e484
