### ISSUE TITLE
[8h] Create logic loading camera in Fit app

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#177]
[Link to Figma](https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-APP?node-id=2071%3A75895)

**Comment by buyalskaya** [comment]
![Image](https://user-images.githubusercontent.com/97980474/184591803-7f083c43-3454-452d-8664-da950c0eca30.png)

**Comment by ZelGaDisA** [comment]
отвлекся на всех по другим вопросам
