### ISSUE TITLE
[8h] Think over new 4 exercises seated for Fit app

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#183]

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=kfP_9z-BtmA&ab_channel=MadFit (2:06) - side to side (лезгинка)

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=kfP_9z-BtmA&ab_channel=MadFit (2:38) - L-arms

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=kfP_9z-BtmA&ab_channel=MadFit (3:43) - prayer push

**Comment by vladimirlabynko** [comment]
https://www.youtube.com/watch?v=yEkKX_dU16M&ab_channel=guidedbyangie (4:50) - butterfly
