### ISSUE TITLE
[8h] Create layout for Fit app (Main screen)

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#59]
Link to Figma mokup https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-FIT---APP?node-id=160%3A151

**Comment by buyalskaya** [comment]
![Image](https://user-images.githubusercontent.com/97980474/178459930-5493615d-57b7-4695-bddc-916e52588a66.PNG)

**Comment by ZelGaDisA** [comment]
ready
