### ISSUE TITLE
[16h] Fix bugs in Fit app

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#67]

**Comment by vladimirlabynko** [comment]
https://github.com/healthUapp/trainer-js/commit/d20a4153120f6d0aac6407a68fe8733a71122e62
https://github.com/healthUapp/trainer-js/commit/ddb8a5ab937b6b61f78d220d5828ad0b1b646409
https://github.com/healthUapp/trainer-js/commit/37ae294e74c85ed8d507e1b32b29b82d7f199e13
https://github.com/healthUapp/trainer-js/commit/3f1d10be308d6f2f24ac477532dac06d7d321186
https://github.com/healthUapp/trainer-js/commit/7230b6aded3361eaf0ed850fd72a14c926fa69de
https://github.com/healthUapp/trainer-js/commit/926cf5d0dc5d259bab7ce37207d95909b6e872c5
