### ISSUE TITLE
[7h]Change the Graph and Stopwatch According to Figma mockup

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#81]
[Link to Figma ](https://www.figma.com/file/QvYWh51xJXVNuAswum8Qtu/hUa-FIT---APP?node-id=243%3A134)

**Comment by dmitrivanich** [comment]
![Image](https://user-images.githubusercontent.com/80646636/180136187-cc1956ae-7105-4902-a0be-3f6bd0d92be0.png)
![Image](https://user-images.githubusercontent.com/80646636/180136186-2a83e42e-93d9-48d5-8d5f-4d3f3713f7f8.png)
