### ISSUE TITLE
[24h] Fix bugs in exercises

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/trainer-js#82]
with @tanyashagova

**Comment by vladimirlabynko** [comment]
https://github.com/healthUapp/trainer-js/commit/06ed94554e0368c0b85c6be0fd67f1dee4c7240c

**Comment by vladimirlabynko** [comment]
https://github.com/healthUapp/trainer-js/commit/5a3c2aeab62833dc0c3c02cff60de9a533c18e01
